### ISSUE TITLE
.htaccess problem in subdirectory

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless#1064]
`  RewriteBase /` is wrong, I need to set it to  ` RewriteBase /hc` to make my website to work.

EDIT: and assets url is wrong too: `http://work.baxandrei.ro/hcuploads/profile_images/profile.jpg`

**Comment by samerton** [comment]
Fixed in 78dca4b66117c8ef45ae178736ec28eeb5e52830 and 520ab351c054087aeeaafa3a81ece9b3fd65a0e6

**Comment by baxandrei** [comment]
Still a problem here: `<div class="jumbotron" style="background-image:url('/hcuploads/profile_images/profile_fire_resized.jpg');" id="personalizare_coperta_profil">`
