### ISSUE TITLE
SQL error when editing post

### ISSUE THREAD

**Issue by rwsender** [NamelessMC/Nameless#117]
So I tried to edit a post on my homepage, got this error when i clicked submit.

SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'label' at row 1

http://puu.sh/nzKs7/929128db7c.png

**Comment by samerton** [comment]
Strange, this should have been fixed several months ago in 7b38dc26aa1a51086e53620401a74cc91d6dd8da

I'll look into the issue in the morning.

**Comment by rwsender** [comment]
anything come of this? still happening with the latest version

**Comment by samerton** [comment]
Does replacing the contents of **pages/forum/edit_post.php** with [this code](https://raw.githubusercontent.com/NamelessMC/Nameless/b47b03f01b8c17874ce800988f47ca1d956d0d99/pages/forum/edit_post.php) help?

**Comment by rwsender** [comment]
brings the same error :(
