### ISSUE TITLE
username_minimum_3 error pops up when it shouldn't

### ISSUE THREAD

**Issue by TiTo-418** [NamelessMC/Nameless#297]
* What kind of issue is it (Question, Bug, etc.)? Bug
* In which version of NamelessMC did it occur (1.x.x)? 6d7eae4
* How would you describe the issue? username_minimum_3 error pops up when it shouldn't
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? http://prntscr.com/bn7cri
* Do you have an idea how or where the issue occurs? Trying to register a 3 characters long username

**Comment by TiTo-418** [comment]
They also don't show up properly on the play page

**Comment by samerton** [comment]
Thanks, fixing now.

**Comment by TiTo-418** [comment]
@samerton Seems like you can't use a 3 digits name on the signin page

**Comment by samerton** [comment]
Do you have a screenshot of the names not showing correctly on the play/infractions pages?

**Comment by TiTo-418** [comment]
@samerton Try registering an 3 character long username, either on the webpage first setup or normally

**Comment by samerton** [comment]
@TiTo-418 Seems to work fine on my end, I've just registered an account named "abc" successfully.

**Comment by partydragen** [comment]
@samerton One i help have this problem on update page and i got him to manually edit the group on that player with 3 letters on database

And i tested on my website soo with 3 letters i have same problem the username can't be 3 letters on update user page i checked the code too now but all looks correct

its worked to signup but not to update the user

**Comment by samerton** [comment]
@partydragen 
The issue preventing you from editing users with username length 3 should have been fixed in 553f1f009ce137e740eabe64e949ad1c00f44e92

**Comment by partydragen** [comment]
@samerton I know that change but it still not working when i tested self on my websites and him i helped with :/

Him i helped had a fresh install of 1.10 but him had the problem

**Comment by partydragen** [comment]
@samerton And now i tested on NamelessMC website by clickig submit on abc user him get error too

**Comment by samerton** [comment]
@partydragen 
The fix was implemented after version 1.0.10, which the Nameless site is running.

**Comment by partydragen** [comment]
@samerton Oh sorry i thinked it was long time before 1.0.10 :package: 

And i now updated the file and can confirm it working ;P
And signin working for me and my other websites and the others i have helped with 3 letters

**Comment by samerton** [comment]
@partydragen 
Glad to hear it's working, I'll mark this as closed as it should now be supported (as of 1.0.11).
