### ISSUE TITLE
Cracked Players can't register

### ISSUE THREAD

**Issue by HappyHarm** [NamelessMC/Nameless#34]
Hi,

It looks like cracked players can't register? They are getting this message each time but I'm sure they are following these conditions:

Please ensure you have filled out all fields, and that your username is between 3 and 20 characters long and your password is between 6 and 30 characters long.

**Comment by HappyHarm** [comment]
Not sure anymore or this is just with cracked people. Sometimes when you get this messages you are registered actually but it doesn't say that.

**Comment by samerton** [comment]
By default, cracked players can't register. To fix this, you can head into the AdminCP's "Minecraft" tab and deactivate the "Enable UUID linking" checkbox.

**Comment by HappyHarm** [comment]
Already did that still not working.

**Comment by samerton** [comment]
Hopefully fixed in 9f16ff02b14b86a5b952ac9b19a4f5b2aaefde26
Can you replace the contents of *pages/register.php* with [this code](https://raw.githubusercontent.com/NamelessMC/Nameless/9f16ff02b14b86a5b952ac9b19a4f5b2aaefde26/pages/register.php)?

**Comment by HappyHarm** [comment]
Of course will try it out now one moment

**Comment by HappyHarm** [comment]
This getting "Please ensure you have filled out all fields, and that your username is between 3 and 20 characters long and your password is between 6 and 30 characters long.".

**Comment by HappyHarm** [comment]
Strange thing btw he is registered actually. It just gives him that error in stead of a register succeful or something like that page.

**Comment by HappyHarm** [comment]
When I'm editing a non premium user on the website in the "Users & Groups" settings it gives me "Your Minecraft name is not a valid Minecraft account." after submitting.

**Comment by samerton** [comment]
I can't reproduce any more issues, upon registering for the first time it works correctly for me. The error will keep appearing as his username already exists, I presume his registration worked correctly the first time.

As for the AdminCP, I'll fix that shortly.

**Comment by samerton** [comment]
Hopefully fixed in e80e6089d76c61bba5ada7f1c5a3bfaf41ce38dd

Can you replace the contents of *pages/admin/users.php* with [this code](https://raw.githubusercontent.com/NamelessMC/Nameless/e80e6089d76c61bba5ada7f1c5a3bfaf41ce38dd/pages/admin/users.php)?

**Comment by HappyHarm** [comment]
Not working. Still can't edit a non premium user http://prntscr.com/98dsja

**Comment by samerton** [comment]
Apologies, appears I only fixed the creation of new users in the AdminCP.

Can you replace the contents of pages/admin/users.php with [this code](https://raw.githubusercontent.com/NamelessMC/Nameless/988672d522f7f66b0ea1c130f105dfd141ee9574/pages/admin/users.php)?

**Comment by HappyHarm** [comment]
It works now, thank you very much for all your help :)
