### ISSUE TITLE
Private Messaging Error

### ISSUE THREAD

**Issue by higoogle1234** [NamelessMC/Nameless#376]
**What kind of issue is it (Question, Bug, etc.)?** Issue.  
**In which version of NamelessMC did it occur (1.x.x)?** Release 1.0.10.  
**How would you describe the issue?** When I hit send on private messaging, an error screen comes up with the following error "SQLSTATE[HY000]: General error: 1364 Field 'content' doesn't have a default value". All boxes are filled and I don't see any problem.
**Do you have (relevant) resources about this issue (Logs, pictures, etc.)?** SQLSTATE[HY000]: General error: 1364 Field 'content' doesn't have a default value
**Do you have an idea how or where the issue occurs?** No idea.

**Comment by samerton** [comment]
This issue was fixed in 774b9ce6ff85652b281828455fdde1d0f55605d6, and the fix will be included in the upcoming version 1.0.11.

**Comment by higoogle1234** [comment]
I changed the code in both files and the problem still occurred. Anything else I need to do?

**Comment by higoogle1234** [comment]
Okay, so when will I be able to have this feature working?

**Comment by samerton** [comment]
@higoogle1234 
I'm hoping to release version 1.0.11 over the next day or two.

**Comment by higoogle1234** [comment]
Hi, there is now another error which says 

"SQLSTATE[HY000]: General error: 1364 Field 'sent_date' doesn't have a default value"

**Comment by higoogle1234** [comment]
This still hasn't been fixed in the latest update :(

**Comment by higoogle1234** [comment]
@samerton Do you know when this will be fixed?
